name: FEMProgramm

channels:
  - conda-forge

dependencies:

  # Python
  - python=3.10

  # BLAS / LAPACK
  - blas=*=mkl
  - mkl
  - mkl-service
  - threadpoolctl

  # Numerik
  - numpy=1.26.4
  - scipy=1.11.4
  - sympy=1.12

  # Sparse FEM Solver
  - suitesparse
  - scikit-sparse=0.4.12

  # Mesh Verarbeitung
  - meshio=5.3.5
  - gmsh=4.11.1

  # Visualisierung
  - pyvista=0.43.10
  - pyvistaqt=0.11.0
  - vtk

  # Plotting
  - matplotlib=3.8.4

  # GUI
  - pyqt=6.7.1

  # Tools
  - packaging
  - pip

  # Pip Pakete
  - pip:
      - PyQt6-sip==13.8.0